# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Superchimp
strapline: strapline or whatever
site_description: >
  I'm a web developer living in Cornwall doing some therapeutic writing about day-to-day things.
author: Peter Mellett
email: pjm@petermellett.co.uk
description: >
  I'm a web developer living in Cornwall doing some therapeutic writing about day-to-day things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petermellett.co.uk" # the base hostname & protocol for your site
twitter_username: mellett68
github_username:  wadtech

paginate: 1
paginate_path: "page:num"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

gems: ['jekyll-paginate']
safe: true
timezone: Europe/London
highlighter: pygments
